export { inject, provide } from './apiInject'
export { h } from './h'
export { renderSlot } from './helpers/renderSlots'
export { createTextVNode } from './vnode'
export { getCurrentInstance } from './component'
export { createRenderer } from './renderer'
export { nextTick } from './scheduler'
