export { createApp } from './createApp'
export { h } from './h'
export { renderSlot } from './helpers/renderSlots'
export { createTextVNode } from './vnode'
export { getCurrentInstance } from './component'
